/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GUI } from "lil-gui";

type GLTFResult = GLTF & {
  nodes: {
    head001: THREE.Mesh;
  };
  materials: {
    ["lambert5.001"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "head.001" | "Key.001|Take 001|BaseLayer.056";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/facecap-23000tri.glb"
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    for (const action of Object.values(actions)) {
      action?.play();
    }
  }, []);

  useEffect(() => {
    const gui = new GUI();
    // gui.close();
    gui.domElement.style.zIndex = "100000000";
    const head = nodes.head001;
    const morphDict = head.morphTargetDictionary;
    if (!morphDict) {
      console.error("No morph target dictionary", head);
      return;
    }
    const influences = head.morphTargetInfluences;

    if (!influences) {
      console.error("No morphTargetInfluences");
      return;
    }

    for (const [key, value] of Object.entries(morphDict)) {
      gui.add(influences, value.toString(), 0, 1, 0.01).name(key).listen(true);
    }
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="head001"
          geometry={nodes.head001.geometry}
          material={materials["lambert5.001"]}
          morphTargetDictionary={nodes.head001.morphTargetDictionary}
          morphTargetInfluences={nodes.head001.morphTargetInfluences}
          position={[-0.04, 0, 0]}
          rotation={[1.5, 0.07, -0.09]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/facecap-23000tri.glb");
