/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lassi Kaukonen (https://sketchfab.com/thesidekick)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/female-hands-7304150ee9084c58b354ea173ca82f39
title: Female hands
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
  };
  materials: {
    Default_OBJ: THREE.MeshStandardMaterial;
    ["Default_OBJ.001"]: THREE.MeshStandardMaterial;
  };
};

const url = "/female_hands/scene.gltf";
export function useFemaleHand() {
  return useGLTF(url) as unknown as GLTFResult;
}
export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(url) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["Default_OBJ.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(url);
